mkdir out

make clean
make TARGET=HIDman_ZX_OSC_INTERNAL_DEBUG OSC_TYPE=OSC_INTERNAL BUILD_OPTIONS=DEBUG
cp ./build/HIDman_ZX_OSC_INTERNAL_DEBUG.bin ./out

make clean
make TARGET=HIDman_ZX_OSC_INTERNAL OSC_TYPE=OSC_INTERNAL
cp ./build/HIDman_ZX_OSC_INTERNAL.bin ./out
